# Netlify configuration for Vite + React SPA
[build]
  command = "npm run build"
  publish = "dist"

# SPA fallback to support client-side routing (React Router, etc.)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200